import { Vehicle } from '@/types/dashboard';

export const getVehicles = (): Vehicle[] => {
  return [
    {
      id: '1',
      name: 'Toyota Camry',
      category: 'Sedan',
      brand: 'Toyota',
      year: 2023,
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 50,
      availability: 'Available',
      location: '15 May',
    },
    {
      id: '2',
      name: 'Toyota Camry',
      category: 'Sedan',
      brand: 'Honda',
      year: 2023,
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 55,
      availability: 'Available',
      location: '14 May',
    },
    {
      id: '3',
      name: 'Honda Accord',
      category: 'Sedan',
      brand: 'Toyota',
      year: 2023,
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 55,
      availability: 'Rented',
      location: '17 May',
    },
    {
      id: '4',
      name: 'Mercedes C-Class',
      category: 'Luxury',
      brand: 'Honda',
      year: 2023,
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 50,
      availability: 'Available',
      location: '13 May',
    },
    {
      id: '5',
      name: 'Honda Accord',
      category: 'Sedan',
      brand: 'Toyota',
      year: 2023,
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 55,
      availability: 'Rented',
      location: '17 May',
    },
    {
      id: '6',
      name: 'Toyota Camry',
      category: 'Luxury',
      brand: 'Toyota',
      year: 2023,
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 120,
      availability: 'Available',
      location: '11 May',
    },
    {
      id: '7',
      name: 'Honda Accord',
      category: 'Luxury',
      brand: 'Honda',
      year: 2023,
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 50,
      availability: 'Available',
      location: '18 May',
    },
  ];
};
