import { Vehicle } from '@/types/dashboard';

export const getVehicles = (): Vehicle[] => {
  return [
    {
      id: '1',
      name: 'Toyota Camry',
      category: 'Sedan',
      brand: 'Toyota',
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 50,
      availability: 'Available',
    },
    {
      id: '2',
      name: 'Toyota Camry',
      category: 'Sedan',
      brand: 'Honda',
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 55,
      availability: 'Available',
    },
    {
      id: '3',
      name: 'Honda Accord',
      category: 'Sedan',
      brand: 'Toyota',
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 55,
      availability: 'Rented',
    },
    {
      id: '4',
      name: 'Mercedes C-Class',
      category: 'Luxury',
      brand: 'Honda',
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 50,
      availability: 'Available',
    },
    {
      id: '5',
      name: 'Honda Accord',
      category: 'Sedan',
      brand: 'Toyota',
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 55,
      availability: 'Rented',
    },
    {
      id: '6',
      name: 'Toyota Camry',
      category: 'Luxury',
      brand: 'Toyota',
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 120,
      availability: 'Available',
    },
    {
      id: '7',
      name: 'Honda Accord',
      category: 'Luxury',
      brand: 'Honda',
      transmission: 'Automatic',
      seating: 5,
      dailyRate: 50,
      availability: 'Available',
    },
  ];
};
